# Metadata
title: Kit France
email:
description: Copyright © 2024 Kit France. All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
linkedin_username: Kit France
github_username: makendon

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

header_pages:
  - about.markdown
  - portfolio.md
  - projects.md
  - blog.markdown

permalink: pretty
