# Metadata
title: Kit France
email:
description: A blog to test GitHub Codespaces
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  makendon

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
  - portfolio.md
  - projects.md
  - blog.markdown

permalink: pretty
